### ISSUE TITLE
iPhone X support with safe area

### ISSUE THREAD

**Issue by shaharukhs** [jvk75/UIImageCropper#4]
Thanks for this Image Cropper,

I am trying to use cropper on iPhone X and cropView and fadeView is not same but on other device it looks perfect...

I am not good in `NSLayoutConstraint.constraints(withVisualFormat:`

I had try to solve issue but no luck for me. 

Please check attachment

![img_0057](https://user-images.githubusercontent.com/16479669/41035006-fe446f7e-69a8-11e8-8642-e89e347a7fca.png)

**Comment by jvk75** [comment]
Hi,

Same "effect" is also in the iOS default picker when edit is enabled and using iPhoneX. I think it's autolayout issue that is only seen in X :(
If you close the UIImagePicker by pressing cancel and retake picture the layout issue is gone which is weird. the miss alignment only happens when screen is layout first time.
I have tried to fix/workaround this but no luck,but it is know and hopefully the real fix will be found soon.

/J

**Comment by shaharukhs** [comment]
Hope you will fix soon, If I get any better luck will update you.

Thanks

**Comment by shaharukhs** [comment]
One thing if I use 

```
let picker = UIImagePickerController()
let cropper = UIImageCropper(cropRatio: 2/3)

cropper.picker = picker
cropper.delegate = self
cropper.cropRatio = 1/1 //(can be set during runtime or in init) //it wont change to 1/1 and always take 2/3 ratio
cropper.cropButtonText = "Crop" // button labes can be localised/changed
cropper.cancelButtonText = "Cancel"
```

> cropper.cropRatio = 1/1 //wont change to 1/1 instead of always takes 2/3 ratio

**Comment by jvk75** [comment]
Sorry about that. I was never meant to be truly runtime. I need to revisit the documantation.
You can set the ratio in cropper init or by setting the parameter before cropper is present. Ratio is fixed when cropper viewDidLoad is called. 
To make that truly dynamic I welcome a PR :)
